/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

typedef volatile unsigned int vuint32_t;
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>

//CLock
#define RCC_BASE 0x40021000
#define RCC_APB2ENR *(volatile uint32_t *)(RCC_BASE + 0x18)
#define RCC_IOPAEN 		(1<<2)
#define RCC_IOPBEN 		(1<<3)
#define RCC_CR      *(volatile uint32_t *)(RCC_BASE + 0x00)

//GPIO Port A
#define GPIOA_BASE 	0x40010800
#define GPIOA_CRH  	*(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_ODR  	*(volatile uint32_t *)(GPIOA_BASE + 0x0C)
#define GPIOA_IDR  	*(volatile uint32_t *)(GPIOA_BASE + 0x08)
#define GPIOA_CRL  	*(volatile uint32_t *)(GPIOA_BASE + 0x00)

#define GPIOA13		(1UL<<13)

//GPIO Port B
#define GPIOB_BASE 	0x40010C00
#define GPIOB_CRH  	*(volatile uint32_t *)(GPIOB_BASE + 0x04)
#define GPIOB_ODR  	*(volatile uint32_t *)(GPIOB_BASE + 0x0C)
#define GPIOB_IDR  	*(volatile uint32_t *)(GPIOB_BASE + 0x08)
#define GPIOB_CRL  	*(volatile uint32_t *)(GPIOB_BASE + 0x00)



void clock_init(){

	RCC_APB2ENR |= RCC_IOPAEN; 	// Enable clock GPIOA
	RCC_APB2ENR |= RCC_IOPBEN; 	// Enable clock GPIOB
}

void GPIO_INIT()
{
	//input pins (A1 - A13)

	//PA1 input HighZ(as externally connected to pull up circuit)
	GPIOA_CRL &= ~(0b11 << 4); //clear register to write on it
	GPIOA_CRL |= (0b01  << 6); //input mode (floating)

	//PA13 input HighZ
	GPIOA_CRH &= ~(0b11 << 20); //act as input
	GPIOA_CRH |= (0b01 << 22); //input mode (floating)

	//output pins (B1 - B13)

	//PB1 Output Push/Pull mode
	//CNF 00:General purpose output push-pull
	GPIOB_CRL &= ~(0b11<<6);      //act as output
	GPIOB_CRL |= (0b01<<4);   //output mode (push-pull)

	//PB13 Output Push/Pull mode
	GPIOB_CRH |= (0b01  << 20);
	GPIOB_CRH &= ~(0b11 << 22);

}

int main(void)
{
	clock_init();
	GPIO_INIT();
	unsigned int i;

	while(1)
	{
		//PA1 >> connected external pull up resistance(PUR) >> default value 1
		if( ( (GPIOA_IDR & (1<<1) ) >> 1 ) == 0)
		{ //PRESS
			GPIOB_ODR ^= (1<<1);
			while( ( (GPIOA_IDR & (1<<1) ) >> 1 ) == 0);//Single press (Loop till hand off the button)
		}

		//PA13 >> connected external PDR >> default value 0
		if( ( (GPIOA_IDR & (1<<13) ) >> 13 ) == 1)
		{ //PRESS
			GPIOB_ODR ^= (1<<13);
		}
		for(i=0; i<20000; i++); //Delay

	}
}
