/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

typedef volatile unsigned int vuint32_t;
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>

//CLock
#define RCC_BASE 0x40021000
#define RCC_APB2ENR *(volatile uint32_t *)(RCC_BASE + 0x18)
#define RCC_IOPAEN 		(1<<2)
#define RCC_CR      *(volatile uint32_t *)(RCC_BASE + 0x00)

//GPIO
#define GPIOA_BASE 	0x40010800
#define GPIOA_CRH  	*(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_ODR  	*(volatile uint32_t *)(GPIOA_BASE + 0x0C)
#define GPIOA_CRL  	*(volatile uint32_t *)(GPIOA_BASE + 0x00)

//EXTI
#define EXTI_BASE	0x40010400
#define EXTI_IMR	*(volatile uint32_t *)(EXTI_BASE + 0x00)
#define EXTI_RTSR	*(volatile uint32_t *)(EXTI_BASE + 0x08)
#define EXTI_PR		*(volatile uint32_t *)(EXTI_BASE + 0x14)


//AFIO
#define AFIO_BASE		0x40010000
#define AFIO_EXTICR1	*(volatile uint32_t *)(AFIO_BASE + 0x08)

//NVIC
#define NVIC_EXTIE0		*(volatile uint32_t *)(0xE000E100)

void clock_init(){
	// Enable clock GPIOA
	RCC_APB2ENR |= RCC_IOPAEN;

	//AFIOEN: Alternate function IO clock enable
	RCC_APB2ENR |=(1<<0);


}

void GPIO_INIT()
{
	//GPIO A Pin 13 port A output
	GPIOA_CRH &=0xFF0FFFFF;
	GPIOA_CRH |=0x00200000;

	//Pin A0 (01):Floating input (reset state)
	GPIOA_CRL |= (1<<2);
}


int main(void)
{
	//init clock
	clock_init();
	//init GPIOA
	GPIO_INIT();

	//EXTI0 configuration to PortA0
	AFIO_EXTICR1 = 0;

	//Enable Rising trigger
	EXTI_RTSR |= (1<<0);

	//Enable EXTI Line 0 (Mask 1)
	EXTI_IMR |= (1<<0);

	//Enable NVIC IRQ6 >> EXI0
	NVIC_EXTIE0 |= (1<<6);

	while(1);
}


void EXTI0_IRQHandler(void)
{
	//IRQ is Happened EXTI0 >>> PortA Pin 0  -> rising edge
	//toggle led pin A 13
	GPIOA_ODR ^= (1<<13) ;

	//disable pending request (to avoid interrupt overhead)
	//Clear pending request for line 0 (write 1 to clear)
	EXTI_PR |= (1<<0);
}
